- name: using vars from inventory
  hosts: local
  connection: local
  tasks:
  - name: printing values from inventory
    ansible.builtin.debug:
      msg: "I'm learning {{ COURSE }}, duration is {{ DURATION }} Hrs and trainer is {{ TRAINER }}"