- name: datatypes in ansible
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps" #string type
    DURATION: 120 #number type
    ISLIVE: true #boolean type
    TOOLS: #list type
    - Linux
    - Shell
    - Ansible
    CONCEPTS: #dictionary type
      CI: "Jenkins"
      SCRIPTING: "Shell, Ansible, Python"
  tasks:
  - name: printing all datatypes
    ansible.builtin.debug:
      msg: "I'm learning {{ COURSE }}, duration is {{ DURATION }}, islive {{ ISLIVE }}, tools are {{ TOOLS }} and concepts are {{ CONCEPTS }}"
