- name: Functions in Ansible
  hosts: local
  connection: local
  tasks:
  - name: using default variable if variable is not given
    ansible.builtin.debug:
      msg: "Hello {{ USER | default('Siva') }}"

  - name: converting string into list using split function
    vars:
      TOOLS: "Linux, Shell, Ansible"
    ansible.builtin.debug:
      msg: "Tools list is {{ TOOLS | split(',') }}"

  - name: converting list items to dictionary
    vars:
      TOOLS: 
      - key: OS
        value: Linux
      - key: Scripting, 
        value: "Shell, Ansible" 
    ansible.builtin.debug:
      msg: "Tools list is {{ TOOLS | items2dict }}"

  - name: converting dictionary items to list
    vars:
      TOOLS: 
        OS: Linux
        SCRIPTING: "Ansible, Shell"
        CI: Jenkins
    ansible.builtin.debug:
      msg: "Tools list is {{ TOOLS | dict2items }}"

  - name: converting to upper alpha
    ansible.builtin.debug:
      msg: "{{ Jayachandra | upper }}"

  - name: converting to lower alpha
    ansible.builtin.debug:
      msg: "{{ Jayachandra | lower }}"      

  