- name: Functions in Ansible
  hosts: local
  connection: local
  tasks:
  - name: using default variable if variable is not given
    ansible.builtin.debug:
      msg: "Hello {{ USER | default('Siva') }}"

  - name: converting string into list using split function
    vars:
      TOOLS: "Linux, Shell, Ansible"
    ansible.builtin.debug:
      msg: "Tools list is {{ TOOLS | split(',') }}"

  - name: converting list items to dictionary
    vars:
      TOOLS: 
      - { OS: Linux }
      - { Scripting: "Shell" }
    ansible.builtin.debug:
      msg: "Tools list is {{ TOOLS | items2dict }}"

  